name: Deploy
run-name: Deploying to VPS
on: [push]
#on:
#  release:
#    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_AFTER: |
            cd /home/${{ secrets.REMOTE_USER }}/dka/scraper
            npm i
            npm run build
            pm2 start /home/${{ secrets.REMOTE_USER }}/scraper/dka-scraper.config.js

