name: Deploy
run-name: Deploying to VPS
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          SCRIPT_AFTER: cd /home/${{ secrets.REMOTE_USER }}/scraper;
            ./start-scraper.sh
          SCRIPT_AFTER_REQUIRED: true
